Radarr qBittorrent Instructions
saltyorg/docs pull request #23
Opened 2022-01-01 18:01 UTC by stayupthetree

Added instructions on how to add qBittorrent as a download client in Radarr

2022-01-01 18:05 UTC, chazlarson requested changes
Also please fix the name of the image.

2022-01-01 18:05 UTC, chazlarson commented on docs/apps/radarr.md
> +		=== "qBittorrent"
Please fix indentation to match others.

2022-01-02 18:34 UTC, stayupthetree commented
indentations fixed and dropped the extra .png

2022-01-02 18:41 UTC, chazlarson approved these changes

2022-01-02 18:41 UTC, merged