Add plex_dupefinder and netdata to mkdocs and index.
saltyorg/docs pull request #64
Opened 2022-06-21 02:08 UTC by RaneyDazed

added 2 more apps that I've actually used to docs. Mainly because I'd heard of them but wasn't sure where to find stuff when i first got into saltbox. Figured it would be nice to add them to docs.

2022-07-04 16:39 UTC, RaneyDazed commented
so should i split this into 2 different PRs? or did i mess something up?

2022-07-05 18:50 UTC, chazlarson requested changes

2022-07-05 19:13 UTC, RaneyDazed commented on docs/sandbox/apps/plex_dupefinder.md
> +- Duplicates can be either in bulk (automatic) or on-by-one (interactively).
should be done

2022-07-08 22:26 UTC, chazlarson approved these changes
LGTM

2022-07-08 22:26 UTC, merged